In [ ]:
# numpy
# Numerical Python



In [1]:
# import numpy module

import numpy as np

NumPy Arrays - The ones() & zeros() Functions
To get started with NumPy arrays, let's create an array having each item as 1 with dimensions 5 blocks, 3 rows and 3 columns.

To create such an array, you first need to import the numpy module at the beginning of the code. Then use the ones() function from the numpy module.

The ones() function requires two inputs. The first input should be the required dimension of the array and the second input should define the data-type of the items in the required array.

In [2]:
# create 1 dimensional array
a1=np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [3]:
type(a1)

numpy.ndarray

In [4]:
# create two dimensional array containing 3 elements in each row. defacto type of an item in numpy is float
a2=np.zeros((2,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
type(a2)

numpy.ndarray

In [6]:
# verify the type of variable
type(a2)

numpy.ndarray

In [7]:
# create a numpy array having 4 blocks, 2 rows and 3 columns
a3=np.zeros((4,2,3))
a3


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
a3=np.zeros((4,2,3),dtype=int)
a3

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [11]:
# using dtype keyword
print("Data type of array=",a2.dtype)
print("data type of array=",a3.dtype)

Data type of array= float64
data type of array= int32


In [12]:
# ndim' and shape keywords
print("Dimension of array a1=",a1.ndim)
print("Dimension of array a2=",a2.ndim)
print("Dimension of array a3=",a3.ndim)


Dimension of array a1= 1
Dimension of array a2= 2
Dimension of array a3= 3


In [ ]:
#shape function

In [13]:
# arange function
np.arange(1,5,2)

array([1, 3])

In [14]:
# arange function
np.arange(11,20).reshape(3,3)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### linspace ()
The linspace() Function: This function creates an array containing a fixed number of numbers
between two specific numbers such that the difference between 
any two consecutive numbers in the array is constant.


In [17]:
# create an array
array=np.linspace(1,10,2)
array

array([ 1., 10.])

In [18]:
array=np.linspace(1,10,5)
array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

The ndarray() Function<br>
we can create a NumPy array containing some random values using ndarray() function.



In [19]:
# generate random numbers 
# we want to create a NumPy array having some random integer values which have 5 rows and 2 columns, then you can use the ndarray() function.

np.ndarray((5,2),dtype=int)


array([[         0, 1072693248],
       [         0, 1074397184],
       [         0, 1075183616],
       [         0, 1075773440],
       [         0, 1076101120]])

In [20]:
# Generating random numbers in numpy
# using np.random.random(size=n)

num1=np.random.random(5)
num1


array([0.00332618, 0.59358922, 0.96764598, 0.67580155, 0.15656937])

In [24]:
# using np.random.randint(low,high,size)
num2=np.random.randint(1,6,2)
num2

array([3, 4])

# using np.random.normal
np.random.normal() is a function provided by NumPy for generating random numbers from a normal (Gaussian) distribution. The function allows you to specify the mean
and standard deviation of the distribution, as well as the shape of the output array.



In [ ]:
# Syntax: np.random.normal(mean, standard_deviation, size)

In [25]:
np.random.normal(5,9,3)

array([1.35770153, 8.13180858, 2.36088298])

In [3]:
import numpy as np

# Generate random numbers from a normal distribution

mean = 0   # Mean of the distribution
std_dev = 1  # Standard deviation of the distribution
size = (3)  # Shape of the output array (3x3 in this case)

random_numbers = np.random.normal(mean, std_dev, size)
print("Random numbers from a normal distribution:")
print(random_numbers)


Random numbers from a normal distribution:
[ 0.8524509  -1.5321829   0.69632136]


The np.random.normal() function is useful for generating random data for simulation, testing,
or any scenario where random numbers from a normal distribution are needed.

In [27]:
# Convert a Python list into a NumPy array using the 'array()' function.

l1=[1,2,3,4]
l1=np.array(l1)
l1

array([1, 2, 3, 4])

In [28]:
l1*2

array([2, 4, 6, 8])

In [29]:
# Syntax: np.random.randint(num1, num2, size=N)
np.random.randint(1,6,3)

array([4, 1, 1])

In [35]:
n1=np.random.randint(1,6,1)
p=int(input("enter any number between 1 to 6: "))
if n1==p:
    print("coreect prediction")
else:
    print("Try one more time")
      


enter any number between 1 to 6: 5
Try one more time


In [ ]:
randnum=np.random.randint(1,6)


for i in range(3):
    user_input=int(input("Enter number between range 1 to 6"))

    if user_input<1 and user_input>6:
        print(" Should be in range 1,6")
    elif randnum == user_input:
        print("You guessed it right")
        break
    else:
        print(" Better luck next time")
   
        
if i>=2:
    print("you ran out of attempts")

In [ ]:
player1=np.random.randint(1,6)
player2=np.random.randint(1,6)

for i in range(3):
    user_input=int(input("Enter any number between range 1 to 6:"))
    
    if user_input<1 and user_input>6:
        print("should be in the range 1,6")
    elif player1==user_input:
        print("Give him one more chance")
    elif player2==user_input:
        print("give him chance")
    elif player1!=user_input:
        print("Give chance to 2 nd player")
    elif player2!=user_input:
        print("Give chance to 1st player")
        break
    else:
        print("Try")
